[ISSUE #713]  Add an logstash-output-rocketmq plugin
apache/rocketmq-externals pull request #714
Opened 2021-05-24 12:46 UTC by hehejiejie

## What is the purpose of the change

Add an logstash-output-rocketmq plugin,named rocketmq-logstash.

## Brief changelog

It is an external which enables logstash to output events to rocketmq.

## Verifying this change

XXXX

Follow this checklist to help us incorporate your contribution quickly and easily. Notice, `it would be helpful if you could finish the following 5 checklist(the last one is not necessary)before request the community to review your PR`.

- [x] Make sure there is a [Github issue](https://github.com/apache/rocketmq/issues) filed for the change (usually before you start working on it). Trivial changes like typos do not require a Github issue. Your pull request should address just this issue, without pulling in other changes - one PR resolves one issue. 
- [x] Format the pull request title like `[ISSUE #123] Fix UnknownException when host config not exist`. Each commit in the pull request should have a meaningful subject line and body.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Write necessary unit-test(over 80% coverage) to verify your logic correction, more mock a little better when cross module dependency exist. If the new feature or significant change is committed, please remember to add integration-test in [test module](https://github.com/apache/rocketmq/tree/master/test).
- [x] Run `mvn -B clean apache-rat:check findbugs:findbugs checkstyle:checkstyle` to make sure basic checks pass. Run `mvn clean install -DskipITs` to make sure unit-test pass. Run `mvn clean test-compile failsafe:integration-test`  to make sure integration-test pass.
- [ ] If this contribution is large, please file an [Apache Individual Contributor License Agreement](http://www.apache.org/licenses/#clas).

2021-05-24 13:00 UTC, vongosling requested changes

2021-05-24 13:00 UTC, vongosling commented on rocketmq-logstash/CONTRIBUTORS
> +* Aaron Mildenstein (untergeek)
Does it contribute to this plugin?

2021-05-24 13:01 UTC, vongosling commented
Do not import some dependencies directly in bin directory.

2021-05-24 13:26 UTC, hehejiejie commented on rocketmq-logstash/CHANGELOG.md
> +  - Docs: Set the default_codec doc attribute.
This project is initialized from an example in [https://github.com/logstash-plugins/logstash-output-example.git](url), so there are some default files I didn't modify.

2021-05-25 00:48 UTC, vongosling commented on rocketmq-logstash/CHANGELOG.md
> +  - Docs: Set the default_codec doc attribute.
You could change it before commit to here.

2021-05-25 03:06 UTC, hehejiejie commented on rocketmq-logstash/CONTRIBUTORS
> +* Aaron Mildenstein (untergeek)
no...

2021-05-25 04:17 UTC, vongosling commented
I will close this pr. and glad to see redacting for the codebase. Pls remember, do not import other code without any declaration here.

2021-05-25 04:17 UTC, closed without merging